---
title: "Kory Illenye - Home"
output: html_document
---

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>
<BR>

# MAT 171

### Syllabus -

* **[Morning Class Syllabus](./Resources/syllabusMAT171summer2018Morning.pdf)**
* **[Evening Class Syllabus](./Resources/syllabusMAT171summer2018Evening.pdf)**

### Calender -

* **[Morning Class Calender](./Resources/morningCalender.pdf)**
* **[Evening Class Calender](./Resources/eveningCalender.pdf)**

### MyMathLab Registration Documents

* **[Morning Class Registration Instructions](./Resources/regC30.pdf)**
* **[Evening Class Registration Instructions](./Resources/regC36.pdf)**

### Notes - 

### Chapter 1

* **[Section 1.1](./Resources/MAT171blitzSectionNotes11Empty.pdf)**
* **[Section 1.2](./Resources/MAT171blitzSectionNotes12Empty.pdf)**
* **[Section 1.3a](./Resources/MAT171blitzSectionNotes13aEmpty.pdf)**
* **[Section 8.1/Section 1.3b](./Resources/MAT171blitzSectionNotes81and13bEmpty.pdf)**
* **[Section 1.4](./Resources/MAT171blitzSectionNotes14Empty.pdf)**
* **[Section 1.7](./Resources/MAT171blitzSectionNotes17Empty.pdf)**
* **[Section 1.5](./Resources/MAT171blitzSectionNotes15Empty.pdf)**
* **Section 1.6**

### Homework

* **[Section 1.2](./Resources/MAT171blitzSectionHW12.pdf)**
* **[Section 1.3a](./Resources/MAT171blitzSectionHW13.pdf)**
* **[Section 8.1/Section 1.3b](./Resources/MAT171blitzSectionHW81and13b.pdf)**
* **[Section 1.4](./Resources/MAT171blitzSectionHW14.pdf)**
* **[Section 1.7](./Resources/MAT171blitzSectionHW17.pdf)**
* **Section 1.5**
* **Section 1.6**


<footer, style="padding-top : 40px;">
<center>

-------







</center>
</footer>